services:
  - type: web
    name: relampago-app
    env: python
    buildCommand: "./build.sh && pip install -r backend/requirements.txt"
    startCommand: "cd backend && python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

